blank_issues_enabled: false
contact_links:
  - name: Amazon Linux 2023 Public Support
    url: https://github.com/amazonlinux/amazon-linux-2023
    about: General public support for Amazon Linux 2023
